### PR TITLE
Upgrade to Angular 12

### LINKED ISSUE #57: Upgrade to newest version Angular
We currently run on `v7.2.0~rc0`, which is obviously not ideal.

Objectives:
* It should be (hopefully) trivial to upgrade to the latest 7.2.x
* It may be slightly harder to upgrade to the newest version of 7.x.x
* Hopefully, we can soon upgrade to the latest version of 8.x.x (at the very least this will require very thorough testing)

### PR DESCRIPTION
**Pull request by bodom0015**
## Problem
Fixes #57

## Approach
* Migrate from Angular v9 to v10
* Migrate from Angular v10 to v11
* Migrate from Angular v11 to v12
* Update dependencies (e.g. TypeScript `4.3.5`)

## How to Test
1. Checkout this branch locally, rebuild the dashboard
2. Login to the WholeTale Dashboard
3. Run a general smoke test of the system
    * You should see that the system behaves precisely as before
    * You should not see any errors in the console (warnings are ok for now, but should disappear soon as well)

### CODE REVIEW

**Comment by craig-willis** [comment]
In general this is working for me.  The only problem I've come across is that the UI no longer detects if a  tale instance is ready -- i.e., I have to refresh the page to get the interactive environment to display. I'm not sure if this is caused by this PR.

**Comment by bodom0015** [comment]
I'm actually having trouble starting any Tale on my dev instance .. I tried with both Jupyter and JupyterLab, but both yielded the same results:
```
executor failed running [/bin/sh -c TIMEFORMAT='time: %3R' bash -c 'time /tmp/install-miniforge.bash' && rm /tmp/install-miniforge.bash /tmp/environment.yml]: exit code: 126

Traceback (most recent call last):
File "/usr/lib/python3.8/site-packages/repo2docker/__main__.py", line 411, in main
r2d.start()
File "/usr/lib/python3.8/site-packages/repo2docker/app.py", line 778, in start
self.build()
File "/usr/lib/python3.8/site-packages/repo2docker/app.py", line 764, in build
raise docker.errors.BuildError(l["error"], build_log="")
ValueError: Error building tale 60fee226407dfefe0a446422
  File "/usr/local/lib/python3.8/dist-packages/celery/app/trace.py", line 412, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/girder_worker/task.py", line 148, in __call__
    results = super(Task, self).__call__(*_t_args, **_t_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/celery/app/trace.py", line 704, in __protected_call__
    return self.run(*args, **kwargs)
  File "/gwvolman/gwvolman/tasks.py", line 469, in build_tale_image
    raise ValueError('Error building tale {}'.format(tale_id))
```

This is also on a fresh system (`make clean && make dev`)
Because I am hitting this error, I haven't been able to reproduce the issue with the Tale not refreshing after launch.

**Comment by craig-willis** [comment]
I just tested launching a tale on master and the UI doesn't detect when it's fully launched without refresh. So this PR isn't the cause.

Will also note for posterity that we determined the cause of your image build problem to be that you needed to configure `experimental=true` for your Docker, which is a newer release than we are running on production (and my dev instance). I'll look into what changed with buildkit support between the versions.

**Comment by bodom0015** [comment]
Merging this since its blocking a few other PRs :+1:

Noting that there is a separate PR (#217) to fix the issue described with the Run > Interact view

**Pull request merged**
