### PR TITLE
Various bugfixes: dropdown behavior, export version, missing icon, add user, apiUrl config, update caniuse

### LINKED ISSUE #235: Odd dropdown behavior on Run > Files
* Dropdown for in Tale > Files > Versions > <some_version> > "v" disappears almost immediately after click, which makes e.g renaming version close to impossible

**Steps to Reproduce**
1. Navigate to Run Tale > Files > Home
2. Upload a file or create a folder, if necessary
3. Expand the dropdown to the right of one of the items in the list
     * You should see a dropdown menu appear
 
**Expected Results**
* Dropdown menu stays open until user clicks elsewhere or chooses an item in the list

**Actual Results**
* Dropdown menu automatically closes after 1-2 seconds

### LINKED ISSUE #236: "Add" user in share tab is permanently disabled
I'm trying to add a collaborator to a Tale, but "Add" button is permanently disabled.
For some reason, `result` in https://github.com/whole-tale/ngx-dashboard/blob/fc1804b9e0e2cb3887df6f021684b18895cc2b94/src/app/%2Brun-tale/run-tale/tale-sharing/tale-sharing.component.ts#L162 is always `null`, even if I select a user.

**Steps to Reproduce**

1. Create a Tale
2. Navigate Tale > Share
3. In "Invite new collaborator" type "admin", select proper account from the dropdown.
4. Click furiously on "Add"

**Expected Results**

User is added.

**Actual Results**

"Add" is grayed-out.

### LINKED ISSUE #237: GIRDER_API_URL env var is no longer respected.
It's not possible to dynamically set girder location anymore.

### How to test?
1. In `docker-compose.yml` set `GIRDER_API_URL` to "https://www.google.com/"
2. Re-deploy

### Expected result
Blank page, since the first call gonna be https://www.google.com/user/me and should fail

### Actual result
Everything works just fine, since dashboard is using hardcoded default...

### LINKED ISSUE #240: Export not working
**Steps to Reproduce**

* Checkout master and rebuild UI
* Create a tale
* Select tale menu > export
* Create a version
* Select version  menu export

**Expected Results**
* Tale is exported for most recent version
* Tale is exported for selected version

**Actual Results**

Nothing happens (no error in console, no requests)

**NOTES**
* Chrome 97.0.4692.71

### LINKED ISSUE #241: RunStatus.RUNNING icon doesn't appear in Recorder Runs panel
See video:

https://user-images.githubusercontent.com/352673/150878958-61e284ff-8548-4104-bcb7-5675db6cdcad.mp4

### How to reproduce?
1. Create a Tale, create a version and a run (provide a valid entrypoint).
2. Navigate to Tale > Files > Recorded Runs
3. Run Recorded Run

### Expected Result
Nice spinning? blue? icon should appear, while the run is running.

### Actual Result
No icon :(

### PR DESCRIPTION
**Pull request by bodom0015**
## Problem
Various small bugs that have been filed recently

Fixes #241 
Fixes #240 
Fixes #237 
Fixes #236 
Fixes #235 

## Approach
* Updated `caniuse` for more accurate browser compatibility hints (this was recommended by our CLI build tools)
* #241: Fixed missing icon for RunStatus.RUNNING - `fa-refresh` no longer appear to work as they did in previous versions of FontAwesome, so `fa-sync` or `fa-sync-alt` should be used instead
* #240: Fixed Export dropdown option for Tale Version on Tale History Panel - `windowService.open` was no longer working as expected
* #237: Fixed `apiUrl` being ignored - the `apiUrl` from `env.json` should once again reflect in the API calls (see note below)
* #236: Fixed "Add" button always being disabled on Run > Share - I suspect that an upgrade might have broken this.. entire method signature appeared different, so some new logic was required here
* #235: Fixed Run > Files dropdown behavior - better change-handling means that this dropdown will only close if something actually changes (e.g. if user changes navs, if user changes the current folder, or if the user uploads a new file to the current folder)

A note about #237 
Because this `apiUrl` needs to be passed into the `ApiModule` on bootstrap, I experimented with a few different patterns using Angular's `APP_INITIALIZERS`, but nothing seemed to provide a smart async method for setting this up after runtime. In the end, I ended up just applying the new `apiUrl` directly from the fetched env (in `WindowService`) onto the existing `ApiConfiguration`. this is probably an anti-pattern for some silly angular reason, but their recommended pattern was overly complex and did not give the correct results, so I'm ok with this 1-line hack if it appears to fix the problem

## How to Test
Prerequisites: at least one Tale created, at least one Version created, ability to Run the Tale

1. Checkout this branch locally, rebuild the dashboard
2. Login to the WholeTale Dashboard
3. Navigate to Run > Files > Recorded Runs for a Tale that you own
4. Create a new Run and wait for it to reach the `RUNNING` state (#241)
    * You should see the spinning arrow icons for the RUNNING state
5. Expand the Tale History Panel on the right and create a new version (if you haven't already)
6. On the timeline below, expand the dropdown beside the new version and choose Export (#240)
    * You should see a new tab open briefly, then close itself, and your file download should begin
7. Edit `env.json` manually, set `apiUrl` to `https://google.com`, save the file, then refresh the UI (#237)
    * You should see many errors in the console, as google.com is not recognized as a valid WholeTale instance
8. Navigate to Run > Share and share with a new user (#236)
    * You should see that the Add button is enabled once a user has been selected from the search prompt
9. Navigate to Run > Files > Tale Workspace and upload a few files to the workspace
10. Expand the dropdown beside one of these files (#235)
    * You should see that the dropdown is more stable, and stays open long enough for the user to actually read the options and interact with it

### CODE REVIEW

**Comment by Xarthisius** [comment]
I'm still seeing #237 . I even did the following:

```diff
--- a/src/app/shared/core/window.service.ts
+++ b/src/app/shared/core/window.service.ts
@@ -13,11 +13,12 @@ export class WindowService implements Window {
   location: any = {};
   env: any = {};
 
-  constructor(private readonly http: HttpClient, private readonly config: ApiConfiguration, private readonly logger: LogService) {
+  constructor(private readonly http: HttpClient, private config: ApiConfiguration, private readonly logger: LogService) {
     this.http.get(ENV_URL).subscribe(
       (env: any) => {
         this.env = env;
         this.config.rootUrl = env.apiUrl;
+        this.logger.error("Read env.json from disk: ", env)
       },
       (err) => {
         this.logger.error('Failed to fetch env: ', err);
```

and I see env.json being read:

```
main.js:1 Read env.json from disk:  {apiUrl: 'https://www.google.com/', dataONEBaseUrl: 'https://cn.dataone.org/cn/v2', authProvider: 'Globus', rtdBaseUrl: 'https://wholetale.readthedocs.io/en/latest'}
```

but requests still go to girder.local.wholetale.org

**Comment by Xarthisius** [comment]
All the linked issues are fixed, thank you! However, I found a new regression potentially introduced by fix for #236.

### How to reproduce?
1. Create a Tale, ensure that you have more than 2 users on your deployment (use `scripts/create_extra_users.py`)
2. Navigate to Tale > Run > Share.
3. Click on a "search user" field to get a suggestion with a list of users.
4. Select the user from the bottom of the list, but make a mental note of user who's at the top.
5. Click "add"

### Expected result
Bottom user is added

### Actual result
Top user is added (my guess whoever is first in the array returned from GET /user)

**Comment by craig-willis** [comment]
> 4. Create a new Run and wait for it to reach the RUNNING state (RunStatus.RUNNING icon doesn't appear in Recorder Runs panel #241)

I see the RUNNING icon, but the state doesn't change from RUNNING to FAILED or SUCCESS without refresh when the job completes successfully or with an error (e.g., run "notfound.sh").

**Comment by bodom0015** [comment]
@Xarthisius I think I've fixed the user search bug... but this still appears very fragile. When it does inevitably break again in the future, I will rip this component out and just rewrite it. For now I've reworked it so that it relies less on the internals of the SemanticUI Search component, but it is potentially susceptible to collisions if two user have the exact same name. I tried to make this work by looking up the user's `login` instead (which would guarantee uniqueness), but this component is not behaving the way I would expect while adjusting the configuration :/


@craig-willis I currently can't reproduce this one, as my Recorded Runs are failing on the "Preparing volumes" stage. Will continue to try and figure out why my runs are failing so I can recreate/fix this one.

My Recorded Runs are failing with the following error:
```bash
CalledProcessError: Command 'girderfs --hostns -c wt_dms --api-url https://girder.dev.wholetale.org/api/v1 --api-key fHFpF1G88PS7UzzypA0br1UHoXOpRU6zdwrIxX0V /var/lib/docker/volumes/62014782368dec78802db292_lambert8_GeXlc3/_data/data 62014783368dec78802db299' returned non-zero exit status 1.
  File "/usr/local/lib/python3.8/dist-packages/celery/app/trace.py", line 412, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/girder_worker/task.py", line 148, in __call__
    results = super(Task, self).__call__(*_t_args, **_t_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/celery/app/trace.py", line 704, in __protected_call__
    return self.run(*args, **kwargs)
  File "/gwvolman/gwvolman/tasks.py", line 713, in recorded_run
    _mount_girderfs(mountpoint, 'data', 'wt_dms', session['_id'], api_key, hostns=True)
  File "/gwvolman/gwvolman/tasks.py", line 600, in _mount_girderfs
    subprocess.check_call(cmd, shell=True)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
```

**Comment by Xarthisius** [comment]
> My Recorded Runs are failing with the following error: .... `--api-url https://girder.dev.wholetale.org/api/v1`
This ^^ is the reason. There's a racing condition between celery worker quering docker for a location of girder and girder being created. Just run: `make restart_worker` and it should go away.

**Comment by bodom0015** [comment]
That did it! I can start runs again, but they all still fail for various "file/directory not found" reasons... 
but that's ok for testing this tho! :D

So I think this last bug that @craig-willis reported is actually an API-side bug, with perhaps some confusion on the presentation side that could be alleviated as well. 
1. The status at the top-right is the status of the `Job`, where the status on Run > Files > Recorded Runs is the status of the `Run`. There will be times when these statuses may be different, which can cause some confusion
2. When I perform runs, they currently all fail but none of them are actually marked as failures in the API:
* my first two are stuck in `STARTING` (runStatus=1) where they failed on "Preparing volumes..."
* my other one is stuck in `RUNNING` (runStatus=2) where it failed with the following:
```
Mounted wt_dms data
Mounted wt_run workspace
Writing the environment to /host/var/lib/docker/volumes/62015a16368dec78802db7a1_lambert8_rSsUpS/_data/workspace/environment.json
Using repo2docker wholetale/repo2docker_wholetale:latest
Starting recorded run
Running Tale with command: sh notfoundasdf.sh
Running image: registry.local.wholetale.org/tale/b3fe3003ade99e0d3b07702430c16712:e1dfc2475659d892e4816590177bf4f2
FileNotFoundError: [Errno 2] No such file or directory: 'ts'
  File "/usr/local/lib/python3.8/dist-packages/celery/app/trace.py", line 412, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/girder_worker/task.py", line 148, in __call__
    results = super(Task, self).__call__(*_t_args, **_t_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/celery/app/trace.py", line 704, in __protected_call__
    return self.run(*args, **kwargs)
  File "/gwvolman/gwvolman/tasks.py", line 751, in recorded_run
    _recorded_run(image_builder.dh.cli, mountpoint, container_config, tag, entrypoint)
  File "/gwvolman/gwvolman/utils.py", line 354, in _recorded_run
    p2 = subprocess.Popen(["ts", '"%Y-%m-%dT%H:%M:%.S"'], stdin=p1.stdout, stdout=dstats_fp)
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
```
3. Finally, I do also see that when changing from `STARTING` to `RUNNING` that the table doesn't update properly, as you had mentioned. I've added some handling there to look for an event where `event.data.resource.type` === `wt_recorded_run`, and force a TaleUpdated signal when that happens. Was this supposed to be a new event type? I feel like this does not quite follow the previous pattern that we used with `wt_tale_updated` and the other signals

**Comment by Xarthisius** [comment]
```FileNotFoundError: [Errno 2] No such file or directory: 'ts'```
that would be caused by an outdated `wholetale/gwvolman:latest` images.

**Review by craig-willis — APPROVED** [review]
* Run status works for me for both success and failure cases, status updates on runs tab on files page.
* Export still works
* Adding users works
* File dropdown works as expected

https://github.com/whole-tale/ngx-dashboard/issues/235: Fixed Run > Files dropdown behavior - better change-handling means that this dropdown will only close if something actually changes (e.g. if user changes navs, if user changes the current folder, or if the user uploads a new file to the current folder)

**Review by Xarthisius — APPROVED** [review]
Looks great! Thank you!

**Pull request merged**
